-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-05 18:26:22 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE admission_request (
    id                  NUMBER(10) NOT NULL,
    user_id             NUMBER(10),
    status_id           NUMBER(10),
    description         VARCHAR2(800 CHAR),
    start_date          DATE NOT NULL,
    finish_date         DATE,
    research_project_id NUMBER(10) NOT NULL
);

COMMENT ON COLUMN admission_request.id IS
    'Auto-generated';

COMMENT ON COLUMN admission_request.description IS
    'Text filled out by petitioning member which is then read by the rgroup leader when reviewing the arequest.';

COMMENT ON COLUMN admission_request.finish_date IS
    'Date that the arequest receives an approved or denied status.';

ALTER TABLE admission_request ADD CONSTRAINT admission_request_pk PRIMARY KEY ( id );

CREATE TABLE admission_status (
    id     NUMBER(10) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN admission_status.id IS
    'Auto-generated';

COMMENT ON COLUMN admission_status.status IS
    'Id:	Status:		Description:
1	new		Not yet seen by the rg leader.
2	pending		Seen by the rg leader but not fully processed.
3	approved	Approved by rgroup leader.
4	denied		Denied by rgroup leader.';

ALTER TABLE admission_status ADD CONSTRAINT admission_status_pk PRIMARY KEY ( id );

CREATE TABLE external_author (
    id         NUMBER(10) NOT NULL,
    first_name VARCHAR2(20 CHAR) NOT NULL,
    last_name  VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN external_author.id IS
    'Auto-generated';

ALTER TABLE external_author ADD CONSTRAINT external_author_pk PRIMARY KEY ( id );

CREATE TABLE faculty (
    id   NUMBER(10) NOT NULL,
    name VARCHAR2(30 CHAR) NOT NULL
);

COMMENT ON COLUMN faculty.id IS
    'Auto-generated';

ALTER TABLE faculty ADD CONSTRAINT faculty_pk PRIMARY KEY ( id );

CREATE TABLE financing_source (
    id     NUMBER(10) NOT NULL,
    source VARCHAR2(15 CHAR) NOT NULL
);

COMMENT ON COLUMN financing_source.id IS
    'Auto-generated';

COMMENT ON COLUMN financing_source.source IS
    'Id:	Status:
1	internal
2	external	';

ALTER TABLE financing_source ADD CONSTRAINT financing_source_pk PRIMARY KEY ( id );

CREATE TABLE financing_type (
    id   NUMBER(10) NOT NULL,
    type VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN financing_type.id IS
    'Auto-generated';

COMMENT ON COLUMN financing_type.type IS
    'Id:	Status:
1	subsidized
2	private	';

ALTER TABLE financing_type ADD CONSTRAINT financing_type_pk PRIMARY KEY ( id );

CREATE TABLE great_rarea (
    id          NUMBER(10) NOT NULL,
    name        VARCHAR2(50 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR) NOT NULL
);

COMMENT ON COLUMN great_rarea.id IS
    'Auto-generated';

COMMENT ON COLUMN great_rarea.name IS
    'Id:	Great rarea:
1	agriculture Sciences
2	social Sciences
3	humanities
4	natural Sciences
5	engineering and IT
6	health and medical sciences';

COMMENT ON COLUMN great_rarea.description IS
    'General description.';

ALTER TABLE great_rarea ADD CONSTRAINT great_rarea_pk PRIMARY KEY ( id );

CREATE TABLE institution (
    id   NUMBER(10) NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL
);

COMMENT ON COLUMN institution.id IS
    'Auto-generated';

COMMENT ON COLUMN institution.name IS
    'Id:	Institution name:					Description:
1	Universidad Icesi';

ALTER TABLE institution ADD CONSTRAINT institution_pk PRIMARY KEY ( id );

CREATE TABLE minciencias_category (
    id       NUMBER(10)
        CONSTRAINT nnc_admission_statusv1_id NOT NULL,
    category VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN minciencias_category.id IS
    'Auto-generated';

COMMENT ON COLUMN minciencias_category.category IS
    'Id:	Category:	Description:
1	A1		Top 25%
2	A		Top 50%
3	B		Top 25%
4	C		Top 0% (2 years experience)
5	D		Top 0% (1 year experience)';

ALTER TABLE minciencias_category ADD CONSTRAINT minciencias_category_pk PRIMARY KEY ( id );

CREATE TABLE publication_author (
    user_id     NUMBER(10) NOT NULL,
    resource_id NUMBER(10) NOT NULL
);

ALTER TABLE publication_author ADD CONSTRAINT publication_author_pk PRIMARY KEY ( resource_id,
                                                                                  user_id );

CREATE TABLE publication_eauthor (
    resource_id        NUMBER(10) NOT NULL,
    external_author_id NUMBER(10) NOT NULL
);

ALTER TABLE publication_eauthor ADD CONSTRAINT publication_eauthor_pk PRIMARY KEY ( external_author_id,
                                                                                    resource_id );

CREATE TABLE research_area (
    id          NUMBER(10) NOT NULL,
    name        VARCHAR2(50 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR) NOT NULL,
    grarea_id   NUMBER(10)
);

COMMENT ON COLUMN research_area.id IS
    'Auto-generated';

COMMENT ON COLUMN research_area.description IS
    'General description.';

COMMENT ON COLUMN research_area.grarea_id IS
    'Great area id';

ALTER TABLE research_area ADD CONSTRAINT research_area_pk PRIMARY KEY ( id );

CREATE TABLE research_group (
    id                    NUMBER(10) NOT NULL,
    name                  VARCHAR2(30 CHAR) NOT NULL,
    leader_id             NUMBER(10) NOT NULL,
    institution_id        NUMBER(10) NOT NULL,
    faculty_id            NUMBER(10) NOT NULL,
    mciencias_id          VARCHAR2(20 CHAR),
    mciencias_category_id NUMBER(10) NOT NULL,
    description           VARCHAR2(4000 CHAR) NOT NULL,
    nprogram_id           NUMBER(10)
);

COMMENT ON COLUMN research_group.id IS
    'Auto-generated';

COMMENT ON COLUMN research_group.name IS
    'Full name of the research group';

COMMENT ON COLUMN research_group.mciencias_id IS
    'Id given by Minciencias to the research group (i.e COL0014387)';

COMMENT ON COLUMN research_group.description IS
    'General description.';

ALTER TABLE research_group ADD CONSTRAINT research_group_pk PRIMARY KEY ( id );

CREATE TABLE research_line (
    id          NUMBER(10) NOT NULL,
    name        VARCHAR2(40 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR) NOT NULL,
    rgroup_id   NUMBER(10) NOT NULL,
    rarea_id    NUMBER(10)
);

COMMENT ON COLUMN research_line.id IS
    'Auto-generated. This entity may also be refered to as ''research discipline''.';

COMMENT ON COLUMN research_line.rarea_id IS
    'Research area id';

ALTER TABLE research_line ADD CONSTRAINT research_line_pk PRIMARY KEY ( id );

CREATE TABLE research_paper (
    id               NUMBER(10) NOT NULL,
    title            VARCHAR2(300 CHAR) NOT NULL,
    academic_journal VARCHAR2(100 CHAR) NOT NULL
);

COMMENT ON COLUMN research_paper.id IS
    'Auto-generated';

COMMENT ON COLUMN research_paper.title IS
    'Full title of the rpaper';

COMMENT ON COLUMN research_paper.academic_journal IS
    'Name of the academic journal that the rpaper was published to.';

ALTER TABLE research_paper ADD CONSTRAINT research_paper_pk PRIMARY KEY ( id );

CREATE TABLE research_project (
    id          NUMBER(10) NOT NULL,
    title       VARCHAR2(300 CHAR) NOT NULL,
    description VARCHAR2(4000 CHAR) NOT NULL,
    start_date  DATE NOT NULL,
    finish_date DATE,
    rline_id    NUMBER(10),
    status_id   NUMBER(10),
    rtype_id    NUMBER(10),
    ftype_id    NUMBER(10),
    fsource_id  NUMBER(10)
);

COMMENT ON COLUMN research_project.id IS
    'Auto-generated';

COMMENT ON COLUMN research_project.title IS
    'Full title of the rproject';

COMMENT ON COLUMN research_project.description IS
    'General description. Also works as a summary';

COMMENT ON COLUMN research_project.finish_date IS
    'Date that the arequest receives an approved or denied status.';

ALTER TABLE research_project ADD CONSTRAINT research_project_pk PRIMARY KEY ( id );

CREATE TABLE "resource" (
    id            NUMBER(10) NOT NULL,
    description   VARCHAR2(500 CHAR) NOT NULL,
    publish_date  DATE NOT NULL,
    rproject_id   NUMBER(10),
    resource_url  VARCHAR2(500 CHAR) NOT NULL,
    visibility_id NUMBER(10)
);

COMMENT ON COLUMN "resource".id IS
    'Auto-generated';

COMMENT ON COLUMN "resource".description IS
    'Public, general description of the publication';

ALTER TABLE "resource" ADD CONSTRAINT resource_pk PRIMARY KEY ( id );

CREATE TABLE resource_visibilities (
    id         NUMBER(10) NOT NULL,
    visibility VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN resource_visibilities.id IS
    'Auto-generated';

COMMENT ON COLUMN resource_visibilities.visibility IS
    'Id:	Visibility:
1	public
2	private	';

ALTER TABLE resource_visibilities ADD CONSTRAINT resource_visibilities_pk PRIMARY KEY ( id );

CREATE TABLE rgroup_leaders (
    rgroup_id               NUMBER(10) NOT NULL,
    leader_id               NUMBER(10) NOT NULL, 
--  Country-issued id
    leader_citizen_id       VARCHAR2(20 CHAR) NOT NULL,
    leader_nationality      VARCHAR2(20 CHAR) NOT NULL,
    leader_second_last_name VARCHAR2(20 CHAR),
    leader_country_of_birth VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE rgroup_leaders ADD CONSTRAINT rgroup_leaders_pk PRIMARY KEY ( rgroup_id,
                                                                          leader_id );

CREATE TABLE rgroup_rproject (
    research_group_id   NUMBER(10) NOT NULL,
    research_project_id NUMBER(10) NOT NULL
);

ALTER TABLE rgroup_rproject ADD CONSTRAINT rgroup_rproject_pk PRIMARY KEY ( research_group_id,
                                                                            research_project_id );

CREATE TABLE rgroup_users (
    research_group_id NUMBER(10) NOT NULL,
    users_id          NUMBER(10) NOT NULL, 
--  Entry date of user to the rgroup
    user_entry        DATE NOT NULL, 
--  Exit date of user to the rgroup
    user_exit         DATE
);

ALTER TABLE rgroup_users ADD CONSTRAINT rgroup_users_pk PRIMARY KEY ( research_group_id,
                                                                      users_id );

CREATE TABLE rproject_goal (
    id          NUMBER(10) NOT NULL,
    description VARCHAR2(500 CHAR) NOT NULL,
    is_finished CHAR(1 CHAR) NOT NULL,
    rproject_id NUMBER(10) NOT NULL
);

COMMENT ON COLUMN rproject_goal.id IS
    'Auto-generated';

COMMENT ON COLUMN rproject_goal.is_finished IS
    'Binary value that shows whether the objective has been completed
Char:	Description:
C	completed
P	pending';

ALTER TABLE rproject_goal ADD CONSTRAINT rproject_goal_pk PRIMARY KEY ( id );

CREATE TABLE rproject_rpapers (
    research_project_id NUMBER(10) NOT NULL,
    research_paper_id   NUMBER(10) NOT NULL, 
--  Special role that helps to identify external authors, i.e, authors that are
--  not registered in the system.
    is_project_member   BLOB NOT NULL
);

ALTER TABLE rproject_rpapers ADD CONSTRAINT rproject_rpapers_pk PRIMARY KEY ( research_project_id,
                                                                              research_paper_id );

CREATE TABLE rproject_status (
    id     NUMBER(10) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN rproject_status.status IS
    'Id:	Status:		Description:
1	planning	
2	design		
3	execution	
4	submission	';

ALTER TABLE rproject_status ADD CONSTRAINT rproject_status_pk PRIMARY KEY ( id );

CREATE TABLE rproject_types (
    id   NUMBER(10) NOT NULL,
    type VARCHAR2(100 CHAR) NOT NULL
);

COMMENT ON COLUMN rproject_types.id IS
    'Auto-generated.';

COMMENT ON COLUMN rproject_types.type IS
    'Id:	Type:						Description:
1	research and development
2	research, development and innovation
3	science technologies accountability and growth	
4	research and creation';

ALTER TABLE rproject_types ADD CONSTRAINT rproject_types_pk PRIMARY KEY ( id );

CREATE TABLE rproject_users (
    research_project_id NUMBER(10) NOT NULL,
    user_id             NUMBER(10) NOT NULL, 
--  Id:	Role:		
--  1	lead author
--  2	co-author
    member_role         VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE rproject_users ADD CONSTRAINT rproject_users_pk PRIMARY KEY ( research_project_id,
                                                                          user_id );

CREATE TABLE sci_ti_national_program (
    id          NUMBER(10) NOT NULL,
    name        VARCHAR2(200 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR) NOT NULL
);

COMMENT ON COLUMN sci_ti_national_program.id IS
    'Auto-generated';

COMMENT ON COLUMN sci_ti_national_program.name IS
    'Id:	Great rarea:
1	biotechnology
2	science, technology and health innovation
3	marine science and hydrobiological resources
4	science, technology and innovation in agricultural science
5	science
6	science, technology and innovation in environment, biodiversity and habitat
7	science, technology and innovation in human science, social sciences and education.
8	science, technology and innovation in TI and communications
9	energy and mining research
10	science, technology and innovation in defense and security
11	science, technology and innovation in geological science
12	science, technology and innovation in engineering';

COMMENT ON COLUMN sci_ti_national_program.description IS
    'General description.';

ALTER TABLE sci_ti_national_program ADD CONSTRAINT sci_ti_national_program_pk PRIMARY KEY ( id );

CREATE TABLE student_program (
    id   NUMBER(10) NOT NULL,
    name VARCHAR2(70 CHAR) NOT NULL
);

COMMENT ON COLUMN student_program.id IS
    'Auto-generated';

ALTER TABLE student_program ADD CONSTRAINT student_program_pk PRIMARY KEY ( id );

CREATE TABLE user_types (
    id   NUMBER(10) NOT NULL,
    type VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN user_types.id IS
    'Auto-generated';

COMMENT ON COLUMN user_types.type IS
    'Id:	Type:
1	professor
2	student';

ALTER TABLE user_types ADD CONSTRAINT user_types_pk PRIMARY KEY ( id );

CREATE TABLE users (
    id            NUMBER(10) NOT NULL,
    username      VARCHAR2(20 CHAR) NOT NULL,
    first_name    VARCHAR2(20 CHAR) NOT NULL,
    last_name     VARCHAR2(20 CHAR) NOT NULL,
    dob           DATE NOT NULL,
    password      VARCHAR2(30 CHAR) NOT NULL,
    email         VARCHAR2(50 CHAR) NOT NULL,
    user_picture  BLOB,
    user_types_id NUMBER(10)
);

COMMENT ON COLUMN users.id IS
    'Id must correspond with id returned from external system accessed through SSO';

COMMENT ON COLUMN users.dob IS
    'Date of birth';

COMMENT ON COLUMN users.user_picture IS
    'Up to 64kb size.';

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( id );

CREATE TABLE users_sprogram (
    user_id            NUMBER(10) NOT NULL,
    student_program_id NUMBER(10) NOT NULL
);

ALTER TABLE users_sprogram ADD CONSTRAINT users_sprogram_pk PRIMARY KEY ( user_id,
                                                                          student_program_id );

ALTER TABLE admission_request
    ADD CONSTRAINT admission_request_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( id )
            ON DELETE CASCADE;

ALTER TABLE admission_request
    ADD CONSTRAINT arequest_astatus_fk FOREIGN KEY ( status_id )
        REFERENCES admission_status ( id );

ALTER TABLE admission_request
    ADD CONSTRAINT arequest_rproject_fk FOREIGN KEY ( research_project_id )
        REFERENCES research_project ( id )
            ON DELETE CASCADE;

ALTER TABLE publication_eauthor
    ADD CONSTRAINT pub_eauthor_eauthor_fk FOREIGN KEY ( external_author_id )
        REFERENCES external_author ( id );

ALTER TABLE publication_eauthor
    ADD CONSTRAINT pub_eauthor_resource_fk FOREIGN KEY ( resource_id )
        REFERENCES "resource" ( id );

ALTER TABLE publication_author
    ADD CONSTRAINT publication_author_resource_fk FOREIGN KEY ( resource_id )
        REFERENCES "resource" ( id );

ALTER TABLE publication_author
    ADD CONSTRAINT publication_author_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( id );

ALTER TABLE "resource"
    ADD CONSTRAINT res_res_visibilities_fk FOREIGN KEY ( visibility_id )
        REFERENCES resource_visibilities ( id );

ALTER TABLE research_area
    ADD CONSTRAINT research_area_great_rarea_fk FOREIGN KEY ( grarea_id )
        REFERENCES great_rarea ( id )
            ON DELETE CASCADE;

ALTER TABLE research_group
    ADD CONSTRAINT research_group_faculty_fk FOREIGN KEY ( faculty_id )
        REFERENCES faculty ( id );

ALTER TABLE research_group
    ADD CONSTRAINT research_group_institution_fk FOREIGN KEY ( institution_id )
        REFERENCES institution ( id );

ALTER TABLE research_line
    ADD CONSTRAINT research_line_research_area_fk FOREIGN KEY ( rarea_id )
        REFERENCES research_area ( id )
            ON DELETE CASCADE;

ALTER TABLE research_paper
    ADD CONSTRAINT research_paper_resource_fk FOREIGN KEY ( id )
        REFERENCES "resource" ( id );

ALTER TABLE "resource"
    ADD CONSTRAINT resource_research_project_fk FOREIGN KEY ( rproject_id )
        REFERENCES research_project ( id );

ALTER TABLE research_group
    ADD CONSTRAINT rgroup_leader_fk FOREIGN KEY ( leader_id )
        REFERENCES users ( id );

ALTER TABLE rgroup_leaders
    ADD CONSTRAINT rgroup_leaders_rgroup_fk FOREIGN KEY ( rgroup_id )
        REFERENCES research_group ( id );

ALTER TABLE research_group
    ADD CONSTRAINT rgroup_mciencias_category_fk FOREIGN KEY ( mciencias_category_id )
        REFERENCES minciencias_category ( id );

ALTER TABLE rgroup_rproject
    ADD CONSTRAINT rgroup_rproject_rgroup_fk FOREIGN KEY ( research_group_id )
        REFERENCES research_group ( id );

ALTER TABLE rgroup_rproject
    ADD CONSTRAINT rgroup_rproject_rproject_fk FOREIGN KEY ( research_project_id )
        REFERENCES research_project ( id );

ALTER TABLE research_group
    ADD CONSTRAINT rgroup_sciti_nat_program_fk FOREIGN KEY ( nprogram_id )
        REFERENCES sci_ti_national_program ( id );

ALTER TABLE rgroup_users
    ADD CONSTRAINT rgroup_users_research_group_fk FOREIGN KEY ( research_group_id )
        REFERENCES research_group ( id );

ALTER TABLE rgroup_users
    ADD CONSTRAINT rgroup_users_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE research_line
    ADD CONSTRAINT rline_rgroup_fk FOREIGN KEY ( rgroup_id )
        REFERENCES research_group ( id )
            ON DELETE CASCADE;

ALTER TABLE research_project
    ADD CONSTRAINT rproject_fin_source_fk FOREIGN KEY ( fsource_id )
        REFERENCES financing_source ( id );

ALTER TABLE research_project
    ADD CONSTRAINT rproject_fin_type_fk FOREIGN KEY ( ftype_id )
        REFERENCES financing_type ( id );

ALTER TABLE rproject_goal
    ADD CONSTRAINT rproject_goal_rproject_fk FOREIGN KEY ( rproject_id )
        REFERENCES research_project ( id );

ALTER TABLE research_project
    ADD CONSTRAINT rproject_rline_fk FOREIGN KEY ( rline_id )
        REFERENCES research_line ( id );

ALTER TABLE rproject_rpapers
    ADD CONSTRAINT rproject_rpapers_rpaper_fk FOREIGN KEY ( research_paper_id )
        REFERENCES research_paper ( id );

ALTER TABLE rproject_rpapers
    ADD CONSTRAINT rproject_rpapers_rproject_fk FOREIGN KEY ( research_project_id )
        REFERENCES research_project ( id );

ALTER TABLE research_project
    ADD CONSTRAINT rproject_rproject_status_fk FOREIGN KEY ( status_id )
        REFERENCES rproject_status ( id );

ALTER TABLE research_project
    ADD CONSTRAINT rproject_rproject_types_fk FOREIGN KEY ( rtype_id )
        REFERENCES rproject_types ( id );

ALTER TABLE rproject_users
    ADD CONSTRAINT rproject_users_rproject_fk FOREIGN KEY ( research_project_id )
        REFERENCES research_project ( id );

ALTER TABLE rproject_users
    ADD CONSTRAINT rproject_users_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( id );

ALTER TABLE users_sprogram
    ADD CONSTRAINT users_sprogram_sprogram_fk FOREIGN KEY ( student_program_id )
        REFERENCES student_program ( id );

ALTER TABLE users_sprogram
    ADD CONSTRAINT users_sprogram_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( id );

ALTER TABLE users
    ADD CONSTRAINT users_user_types_fk FOREIGN KEY ( user_types_id )
        REFERENCES user_types ( id );

CREATE SEQUENCE admission_request_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER admission_request_id_trg BEFORE
    INSERT ON admission_request
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := admission_request_id_seq.nextval;
END;
/

CREATE SEQUENCE admission_status_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER admission_status_id_trg BEFORE
    INSERT ON admission_status
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := admission_status_id_seq.nextval;
END;
/

CREATE SEQUENCE external_author_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER external_author_id_trg BEFORE
    INSERT ON external_author
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := external_author_id_seq.nextval;
END;
/

CREATE SEQUENCE faculty_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER faculty_id_trg BEFORE
    INSERT ON faculty
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := faculty_id_seq.nextval;
END;
/

CREATE SEQUENCE financing_source_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER financing_source_id_trg BEFORE
    INSERT ON financing_source
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := financing_source_id_seq.nextval;
END;
/

CREATE SEQUENCE financing_type_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER financing_type_id_trg BEFORE
    INSERT ON financing_type
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := financing_type_id_seq.nextval;
END;
/

CREATE SEQUENCE great_rarea_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER great_rarea_id_trg BEFORE
    INSERT ON great_rarea
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := great_rarea_id_seq.nextval;
END;
/

CREATE SEQUENCE institution_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER institution_id_trg BEFORE
    INSERT ON institution
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := institution_id_seq.nextval;
END;
/

CREATE SEQUENCE minciencias_category_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER minciencias_category_id_trg BEFORE
    INSERT ON minciencias_category
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := minciencias_category_id_seq.nextval;
END;
/

CREATE SEQUENCE research_area_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER research_area_id_trg BEFORE
    INSERT ON research_area
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := research_area_id_seq.nextval;
END;
/

CREATE SEQUENCE rg_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rg_id_trg BEFORE
    INSERT ON research_group
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := rg_id_seq.nextval;
END;
/

CREATE SEQUENCE research_line_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER research_line_id_trg BEFORE
    INSERT ON research_line
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := research_line_id_seq.nextval;
END;
/

CREATE SEQUENCE research_project_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER research_project_id_trg BEFORE
    INSERT ON research_project
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := research_project_id_seq.nextval;
END;
/

CREATE SEQUENCE resource_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER resource_id_trg BEFORE
    INSERT ON "resource"
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := resource_id_seq.nextval;
END;
/

CREATE SEQUENCE resource_visibilities_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER resource_visibilities_id_trg BEFORE
    INSERT ON resource_visibilities
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := resource_visibilities_id_seq.nextval;
END;
/

CREATE SEQUENCE rproject_goal_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rproject_goal_id_trg BEFORE
    INSERT ON rproject_goal
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := rproject_goal_id_seq.nextval;
END;
/

CREATE SEQUENCE sci_ti_national_program_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER sci_ti_national_program_id_trg BEFORE
    INSERT ON sci_ti_national_program
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := sci_ti_national_program_id_seq.nextval;
END;
/

CREATE SEQUENCE student_program_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER student_program_id_trg BEFORE
    INSERT ON student_program
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := student_program_id_seq.nextval;
END;
/

CREATE SEQUENCE user_types_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER user_types_id_trg BEFORE
    INSERT ON user_types
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := user_types_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            31
-- CREATE INDEX                             0
-- ALTER TABLE                             67
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          19
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         19
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
