package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ExternalAuthor generated by hbm2java
 */
public class ExternalAuthor implements java.io.Serializable {

	private long id;
	private String firstName;
	private String lastName;
	private Set resources = new HashSet(0);

	public ExternalAuthor() {
	}

	public ExternalAuthor(long id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public ExternalAuthor(long id, String firstName, String lastName, Set resources) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.resources = resources;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

}
