package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * FinancingSource generated by hbm2java
 */
public class FinancingSource implements java.io.Serializable {

	private long id;
	private String source;
	private Set researchProjects = new HashSet(0);

	public FinancingSource() {
	}

	public FinancingSource(long id, String source) {
		this.id = id;
		this.source = source;
	}

	public FinancingSource(long id, String source, Set researchProjects) {
		this.id = id;
		this.source = source;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Set getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set researchProjects) {
		this.researchProjects = researchProjects;
	}

}
