package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

/**
 * FinancingSource generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class FinancingSource implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String source;
	
	@OneToMany(mappedBy = "financingSource")
	private Set<ResearchProject> researchProjects;

	public FinancingSource() {
	}

	public FinancingSource(long id, String source) {
		this.id = id;
		this.source = source;
	}

	public FinancingSource(long id, String source, Set<ResearchProject> researchProjects) {
		this.id = id;
		this.source = source;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Set<ResearchProject> getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set<ResearchProject> researchProjects) {
		this.researchProjects = researchProjects;
	}

}
