package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * GreatRarea generated by hbm2java
 */
@Entity
public class GreatRarea implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private String name;
	private String description;
	private Set researchAreas = new HashSet(0);

	public GreatRarea() {
	}

	public GreatRarea(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public GreatRarea(long id, String name, String description, Set researchAreas) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.researchAreas = researchAreas;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getResearchAreas() {
		return this.researchAreas;
	}

	public void setResearchAreas(Set researchAreas) {
		this.researchAreas = researchAreas;
	}

}
