package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * GreatRarea generated by hbm2java
 */
import javax.persistence.OneToMany;

@Entity
public class GreatRarea implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String name;
	private String description;
	
	@OneToMany(mappedBy = "greatRarea")
	private Set<ResearchArea> researchAreas;

	public GreatRarea() {
	}

	public GreatRarea(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public GreatRarea(long id, String name, String description, Set<ResearchArea> researchAreas) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.researchAreas = researchAreas;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ResearchArea> getResearchAreas() {
		return this.researchAreas;
	}

	public void setResearchAreas(Set<ResearchArea> researchAreas) {
		this.researchAreas = researchAreas;
	}

}
