package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Institution generated by hbm2java
 */
import javax.persistence.OneToMany;

@Entity
public class Institution implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String name;
	
	@OneToMany(mappedBy = "institution")
	private Set<ResearchGroup> researchGroups;

	public Institution() {
	}

	public Institution(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Institution(long id, String name, Set<ResearchGroup> researchGroups) {
		this.id = id;
		this.name = name;
		this.researchGroups = researchGroups;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}

}
