package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Institution generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Institution implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private String name;
	private Set researchGroups = new HashSet(0);

	public Institution() {
	}

	public Institution(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Institution(long id, String name, Set researchGroups) {
		this.id = id;
		this.name = name;
		this.researchGroups = researchGroups;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set researchGroups) {
		this.researchGroups = researchGroups;
	}

}
