package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * ResearchPaper generated by hbm2java
 */
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class ResearchPaper implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_id")
	private Resource resource;
	
	private String title;
	private String academicJournal;
	
	@OneToMany(mappedBy = "researchPaper")
	private Set<RprojectRpapers> rprojectRpapers;

	public ResearchPaper() {
	}

	public ResearchPaper(Resource resource, String title, String academicJournal) {
		this.resource = resource;
		this.title = title;
		this.academicJournal = academicJournal;
	}

	public ResearchPaper(Resource resource, String title, String academicJournal, Set<RprojectRpapers> rprojectRpaperses) {
		this.resource = resource;
		this.title = title;
		this.academicJournal = academicJournal;
		this.rprojectRpapers = rprojectRpaperses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAcademicJournal() {
		return this.academicJournal;
	}

	public void setAcademicJournal(String academicJournal) {
		this.academicJournal = academicJournal;
	}

	public Set<RprojectRpapers> getRprojectRpaperses() {
		return this.rprojectRpapers;
	}

	public void setRprojectRpaperses(Set<RprojectRpapers> rprojectRpaperses) {
		this.rprojectRpapers = rprojectRpaperses;
	}

}
