package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ResearchLine generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class ResearchLine implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private ResearchArea researchArea;
	private ResearchGroup researchGroup;
	private String name;
	private String description;
	private Set researchProjects = new HashSet(0);

	public ResearchLine() {
	}

	public ResearchLine(long id, ResearchGroup researchGroup, String name, String description) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.name = name;
		this.description = description;
	}

	public ResearchLine(long id, ResearchArea researchArea, ResearchGroup researchGroup, String name,
			String description, Set researchProjects) {
		this.id = id;
		this.researchArea = researchArea;
		this.researchGroup = researchGroup;
		this.name = name;
		this.description = description;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ResearchArea getResearchArea() {
		return this.researchArea;
	}

	public void setResearchArea(ResearchArea researchArea) {
		this.researchArea = researchArea;
	}

	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set researchProjects) {
		this.researchProjects = researchProjects;
	}

}
