package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

/**
 * ResearchGroup generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class ResearchGroup implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "faculty_id")
	private Faculty faculty;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "institution_id")
	private Institution institution;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "minciencias_category_id")
	private MincienciasCategory mincienciasCategory;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sci_ti_nprogram_id")
	private SciTiNationalProgram sciTiNationalProgram;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	private Users users;
	
	private String name;
	private String description;
	
	@OneToMany(mappedBy = "researchGroup")
	private Set<AdmissionRequest> admissionRequests;
	
	@OneToMany(mappedBy = "researchGroup")
	private Set<RgroupUsers> rgroupUsers;
	
	@OneToMany(mappedBy = "researchGroup")
	private Set<ResearchLine> researchLines;
	
	@OneToMany(mappedBy = "researchGroup")
	private Set<RgroupLeaders> rgroupLeaders;
	
	@ManyToMany
	@JoinTable(
			  name = "rgroup_rproject", 
			  joinColumns = @JoinColumn(name = "research_group_id"), 
			  inverseJoinColumns = @JoinColumn(name = "research_project_id"))
	private Set<ResearchProject> researchProjects;

	public ResearchGroup() {
	}

	public ResearchGroup(long id, Faculty faculty, Institution institution, MincienciasCategory mincienciasCategory,
			Users users, String name, String description) {
		this.id = id;
		this.faculty = faculty;
		this.institution = institution;
		this.mincienciasCategory = mincienciasCategory;
		this.users = users;
		this.name = name;
		this.description = description;
	}

	public ResearchGroup(long id, Faculty faculty, Institution institution, MincienciasCategory mincienciasCategory,
			SciTiNationalProgram sciTiNationalProgram, Users users, String name, String description,
			Set<AdmissionRequest> admissionRequests, Set<RgroupUsers> rgroupUsers, Set<ResearchLine> researchLines, Set<RgroupLeaders> rgroupLeaders, Set<ResearchProject> researchProjects) {
		this.id = id;
		this.faculty = faculty;
		this.institution = institution;
		this.mincienciasCategory = mincienciasCategory;
		this.sciTiNationalProgram = sciTiNationalProgram;
		this.users = users;
		this.name = name;
		this.description = description;
		this.admissionRequests = admissionRequests;
		this.rgroupUsers = rgroupUsers;
		this.researchLines = researchLines;
		this.rgroupLeaders = rgroupLeaders;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	public MincienciasCategory getMincienciasCategory() {
		return this.mincienciasCategory;
	}

	public void setMincienciasCategory(MincienciasCategory mincienciasCategory) {
		this.mincienciasCategory = mincienciasCategory;
	}

	public SciTiNationalProgram getSciTiNationalProgram() {
		return this.sciTiNationalProgram;
	}

	public void setSciTiNationalProgram(SciTiNationalProgram sciTiNationalProgram) {
		this.sciTiNationalProgram = sciTiNationalProgram;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<AdmissionRequest> getAdmissionRequests() {
		return this.admissionRequests;
	}

	public void setAdmissionRequests(Set<AdmissionRequest> admissionRequests) {
		this.admissionRequests = admissionRequests;
	}

	public Set<RgroupUsers> getRgroupUserses() {
		return this.rgroupUsers;
	}

	public void setRgroupUserses(Set<RgroupUsers> rgroupUserses) {
		this.rgroupUsers = rgroupUserses;
	}

	public Set<ResearchLine> getResearchLines() {
		return this.researchLines;
	}

	public void setResearchLines(Set<ResearchLine> researchLines) {
		this.researchLines = researchLines;
	}

	public Set<RgroupLeaders> getRgroupLeaderses() {
		return this.rgroupLeaders;
	}

	public void setRgroupLeaderses(Set<RgroupLeaders> rgroupLeaderses) {
		this.rgroupLeaders = rgroupLeaderses;
	}

	public Set<ResearchProject> getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set<ResearchProject> researchProjects) {
		this.researchProjects = researchProjects;
	}

}
