// default package
// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResearchProject generated by hbm2java
 */
public class ResearchProject implements java.io.Serializable {

	private long id;
	private FinancingSource financingSource;
	private FinancingType financingType;
	private ResearchLine researchLine;
	private RprojectStatus rprojectStatus;
	private RprojectTypes rprojectTypes;
	private String title;
	private String description;
	private Date startDate;
	private Date finishDate;
	private Set researchGroups = new HashSet(0);
	private Set rprojectRpaperses = new HashSet(0);
	private Set resources = new HashSet(0);
	private Set rprojectGoals = new HashSet(0);
	private Set rprojectUserses = new HashSet(0);

	public ResearchProject() {
	}

	public ResearchProject(long id, String title, String description, Date startDate) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.startDate = startDate;
	}

	public ResearchProject(long id, FinancingSource financingSource, FinancingType financingType,
			ResearchLine researchLine, RprojectStatus rprojectStatus, RprojectTypes rprojectTypes, String title,
			String description, Date startDate, Date finishDate, Set researchGroups, Set rprojectRpaperses,
			Set resources, Set rprojectGoals, Set rprojectUserses) {
		this.id = id;
		this.financingSource = financingSource;
		this.financingType = financingType;
		this.researchLine = researchLine;
		this.rprojectStatus = rprojectStatus;
		this.rprojectTypes = rprojectTypes;
		this.title = title;
		this.description = description;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.researchGroups = researchGroups;
		this.rprojectRpaperses = rprojectRpaperses;
		this.resources = resources;
		this.rprojectGoals = rprojectGoals;
		this.rprojectUserses = rprojectUserses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public FinancingSource getFinancingSource() {
		return this.financingSource;
	}

	public void setFinancingSource(FinancingSource financingSource) {
		this.financingSource = financingSource;
	}

	public FinancingType getFinancingType() {
		return this.financingType;
	}

	public void setFinancingType(FinancingType financingType) {
		this.financingType = financingType;
	}

	public ResearchLine getResearchLine() {
		return this.researchLine;
	}

	public void setResearchLine(ResearchLine researchLine) {
		this.researchLine = researchLine;
	}

	public RprojectStatus getRprojectStatus() {
		return this.rprojectStatus;
	}

	public void setRprojectStatus(RprojectStatus rprojectStatus) {
		this.rprojectStatus = rprojectStatus;
	}

	public RprojectTypes getRprojectTypes() {
		return this.rprojectTypes;
	}

	public void setRprojectTypes(RprojectTypes rprojectTypes) {
		this.rprojectTypes = rprojectTypes;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Set getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set researchGroups) {
		this.researchGroups = researchGroups;
	}

	public Set getRprojectRpaperses() {
		return this.rprojectRpaperses;
	}

	public void setRprojectRpaperses(Set rprojectRpaperses) {
		this.rprojectRpaperses = rprojectRpaperses;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

	public Set getRprojectGoals() {
		return this.rprojectGoals;
	}

	public void setRprojectGoals(Set rprojectGoals) {
		this.rprojectGoals = rprojectGoals;
	}

	public Set getRprojectUserses() {
		return this.rprojectUserses;
	}

	public void setRprojectUserses(Set rprojectUserses) {
		this.rprojectUserses = rprojectUserses;
	}

}
