// default package
// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ResearchGroup generated by hbm2java
 */
public class ResearchGroup implements java.io.Serializable {

	private long id;
	private Faculty faculty;
	private Institution institution;
	private SciTiNationalProgram sciTiNationalProgram;
	private Users users;
	private String name;
	private String colcienciasCategory;
	private String description;
	private String citizenId;
	private String nationality;
	private String secondLastName;
	private String countryOfBirth;
	private Set admissionRequests = new HashSet(0);
	private Set rgroupUserses = new HashSet(0);
	private Set researchLines = new HashSet(0);
	private Set researchProjects = new HashSet(0);

	public ResearchGroup() {
	}

	public ResearchGroup(long id, Users users, String name, String colcienciasCategory, String description,
			String citizenId, String nationality, String countryOfBirth) {
		this.id = id;
		this.users = users;
		this.name = name;
		this.colcienciasCategory = colcienciasCategory;
		this.description = description;
		this.citizenId = citizenId;
		this.nationality = nationality;
		this.countryOfBirth = countryOfBirth;
	}

	public ResearchGroup(long id, Faculty faculty, Institution institution, SciTiNationalProgram sciTiNationalProgram,
			Users users, String name, String colcienciasCategory, String description, String citizenId,
			String nationality, String secondLastName, String countryOfBirth, Set admissionRequests, Set rgroupUserses,
			Set researchLines, Set researchProjects) {
		this.id = id;
		this.faculty = faculty;
		this.institution = institution;
		this.sciTiNationalProgram = sciTiNationalProgram;
		this.users = users;
		this.name = name;
		this.colcienciasCategory = colcienciasCategory;
		this.description = description;
		this.citizenId = citizenId;
		this.nationality = nationality;
		this.secondLastName = secondLastName;
		this.countryOfBirth = countryOfBirth;
		this.admissionRequests = admissionRequests;
		this.rgroupUserses = rgroupUserses;
		this.researchLines = researchLines;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	public SciTiNationalProgram getSciTiNationalProgram() {
		return this.sciTiNationalProgram;
	}

	public void setSciTiNationalProgram(SciTiNationalProgram sciTiNationalProgram) {
		this.sciTiNationalProgram = sciTiNationalProgram;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getColcienciasCategory() {
		return this.colcienciasCategory;
	}

	public void setColcienciasCategory(String colcienciasCategory) {
		this.colcienciasCategory = colcienciasCategory;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCitizenId() {
		return this.citizenId;
	}

	public void setCitizenId(String citizenId) {
		this.citizenId = citizenId;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getSecondLastName() {
		return this.secondLastName;
	}

	public void setSecondLastName(String secondLastName) {
		this.secondLastName = secondLastName;
	}

	public String getCountryOfBirth() {
		return this.countryOfBirth;
	}

	public void setCountryOfBirth(String countryOfBirth) {
		this.countryOfBirth = countryOfBirth;
	}

	public Set getAdmissionRequests() {
		return this.admissionRequests;
	}

	public void setAdmissionRequests(Set admissionRequests) {
		this.admissionRequests = admissionRequests;
	}

	public Set getRgroupUserses() {
		return this.rgroupUserses;
	}

	public void setRgroupUserses(Set rgroupUserses) {
		this.rgroupUserses = rgroupUserses;
	}

	public Set getResearchLines() {
		return this.researchLines;
	}

	public void setResearchLines(Set researchLines) {
		this.researchLines = researchLines;
	}

	public Set getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set researchProjects) {
		this.researchProjects = researchProjects;
	}

}
