package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:23:43 PM by Hibernate Tools 5.6.7.Final

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import java.util.HashSet;
import java.util.Set;

/**
 * ResearchGroup generated by hbm2java
 */
@Entity
public class ResearchGroup implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private Faculty faculty;
	private Institution institution;
	private MincienciasCategory mincienciasCategory;
	private SciTiNationalProgram sciTiNationalProgram;
	private String name;
	private String description;
	private Set admissionRequests = new HashSet(0);
	private Set rgroupUserses = new HashSet(0);
	private Set researchLines = new HashSet(0);
	private Set rgroupLeaderses = new HashSet(0);
	private Set researchProjects = new HashSet(0);

	public ResearchGroup() {
	}

	public ResearchGroup(long id, Faculty faculty, Institution institution, MincienciasCategory mincienciasCategory,
			String name, String description) {
		this.id = id;
		this.faculty = faculty;
		this.institution = institution;
		this.mincienciasCategory = mincienciasCategory;
		this.name = name;
		this.description = description;
	}

	public ResearchGroup(long id, Faculty faculty, Institution institution, MincienciasCategory mincienciasCategory,
			SciTiNationalProgram sciTiNationalProgram, String name, String description, Set admissionRequests,
			Set rgroupUserses, Set researchLines, Set rgroupLeaderses, Set researchProjects) {
		this.id = id;
		this.faculty = faculty;
		this.institution = institution;
		this.mincienciasCategory = mincienciasCategory;
		this.sciTiNationalProgram = sciTiNationalProgram;
		this.name = name;
		this.description = description;
		this.admissionRequests = admissionRequests;
		this.rgroupUserses = rgroupUserses;
		this.researchLines = researchLines;
		this.rgroupLeaderses = rgroupLeaderses;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	public MincienciasCategory getMincienciasCategory() {
		return this.mincienciasCategory;
	}

	public void setMincienciasCategory(MincienciasCategory mincienciasCategory) {
		this.mincienciasCategory = mincienciasCategory;
	}

	public SciTiNationalProgram getSciTiNationalProgram() {
		return this.sciTiNationalProgram;
	}

	public void setSciTiNationalProgram(SciTiNationalProgram sciTiNationalProgram) {
		this.sciTiNationalProgram = sciTiNationalProgram;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getAdmissionRequests() {
		return this.admissionRequests;
	}

	public void setAdmissionRequests(Set admissionRequests) {
		this.admissionRequests = admissionRequests;
	}

	public Set getRgroupUserses() {
		return this.rgroupUserses;
	}

	public void setRgroupUserses(Set rgroupUserses) {
		this.rgroupUserses = rgroupUserses;
	}

	public Set getResearchLines() {
		return this.researchLines;
	}

	public void setResearchLines(Set researchLines) {
		this.researchLines = researchLines;
	}

	public Set getRgroupLeaderses() {
		return this.rgroupLeaderses;
	}

	public void setRgroupLeaderses(Set rgroupLeaderses) {
		this.rgroupLeaderses = rgroupLeaderses;
	}

	public Set getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set researchProjects) {
		this.researchProjects = researchProjects;
	}

}
