package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ResearchPaper generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class ResearchPaper implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private Resource resource;
	private String title;
	private String academicJournal;
	private Set rprojectRpaperses = new HashSet(0);

	public ResearchPaper() {
	}

	public ResearchPaper(Resource resource, String title, String academicJournal) {
		this.resource = resource;
		this.title = title;
		this.academicJournal = academicJournal;
	}

	public ResearchPaper(Resource resource, String title, String academicJournal, Set rprojectRpaperses) {
		this.resource = resource;
		this.title = title;
		this.academicJournal = academicJournal;
		this.rprojectRpaperses = rprojectRpaperses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAcademicJournal() {
		return this.academicJournal;
	}

	public void setAcademicJournal(String academicJournal) {
		this.academicJournal = academicJournal;
	}

	public Set getRprojectRpaperses() {
		return this.rprojectRpaperses;
	}

	public void setRprojectRpaperses(Set rprojectRpaperses) {
		this.rprojectRpaperses = rprojectRpaperses;
	}

}
