package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * ResearchProject generated by hbm2java
 */
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class ResearchProject implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "financing_source_id")
	private FinancingSource financingSource;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "financing_type_id")
	private FinancingType financingType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "research_line_id")
	private ResearchLine researchLine;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rproject_status_id")
	private RprojectStatus rprojectStatus;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rproject_type_id")
	private RprojectTypes rprojectType;
	
	private String title;
	private String description;
	private Date startDate;
	private Date finishDate;
	
	@ManyToMany(mappedBy = "researchProjects")
	private Set<ResearchGroup> researchGroups;
	
	@OneToMany(mappedBy = "researchProject")
	private Set<RprojectRpapers> rprojectRpapers;
	
	@OneToMany(mappedBy = "researchProject")
	private Set<Resource> resources;
	
	@OneToMany(mappedBy = "researchProject")
	private Set<RprojectGoal> rprojectGoals;
	
	@OneToMany(mappedBy = "researchProject")
	private Set<RprojectUsers> rprojectUsers;

	public ResearchProject() {
	}

	public ResearchProject(long id, String title, String description, Date startDate) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.startDate = startDate;
	}

	public ResearchProject(long id, FinancingSource financingSource, FinancingType financingType,
			ResearchLine researchLine, RprojectStatus rprojectStatus, RprojectTypes rprojectTypes, String title,
			String description, Date startDate, Date finishDate, Set<ResearchGroup> researchGroups, Set<RprojectRpapers> rprojectRpapers,
			Set<Resource> resources, Set<RprojectGoal> rprojectGoals, Set<RprojectUsers> rprojectUsers) {
		this.id = id;
		this.financingSource = financingSource;
		this.financingType = financingType;
		this.researchLine = researchLine;
		this.rprojectStatus = rprojectStatus;
		this.rprojectType = rprojectTypes;
		this.title = title;
		this.description = description;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.researchGroups = researchGroups;
		this.rprojectRpapers = rprojectRpapers;
		this.resources = resources;
		this.rprojectGoals = rprojectGoals;
		this.rprojectUsers = rprojectUsers;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public FinancingSource getFinancingSource() {
		return this.financingSource;
	}

	public void setFinancingSource(FinancingSource financingSource) {
		this.financingSource = financingSource;
	}

	public FinancingType getFinancingType() {
		return this.financingType;
	}

	public void setFinancingType(FinancingType financingType) {
		this.financingType = financingType;
	}

	public ResearchLine getResearchLine() {
		return this.researchLine;
	}

	public void setResearchLine(ResearchLine researchLine) {
		this.researchLine = researchLine;
	}

	public RprojectStatus getRprojectStatus() {
		return this.rprojectStatus;
	}

	public void setRprojectStatus(RprojectStatus rprojectStatus) {
		this.rprojectStatus = rprojectStatus;
	}

	public RprojectTypes getRprojectTypes() {
		return this.rprojectType;
	}

	public void setRprojectTypes(RprojectTypes rprojectTypes) {
		this.rprojectType = rprojectTypes;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}

	public Set<RprojectRpapers> getRprojectRpaperses() {
		return this.rprojectRpapers;
	}

	public void setRprojectRpaperses(Set<RprojectRpapers> rprojectRpapers) {
		this.rprojectRpapers = rprojectRpapers;
	}

	public Set<Resource> getResources() {
		return this.resources;
	}

	public void setResources(Set<Resource> resources) {
		this.resources = resources;
	}

	public Set<RprojectGoal> getRprojectGoals() {
		return this.rprojectGoals;
	}

	public void setRprojectGoals(Set<RprojectGoal> rprojectGoals) {
		this.rprojectGoals = rprojectGoals;
	}

	public Set<RprojectUsers> getRprojectUserses() {
		return this.rprojectUsers;
	}

	public void setRprojectUserses(Set<RprojectUsers> rprojectUsers) {
		this.rprojectUsers = rprojectUsers;
	}

}
