package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

/**
 * ResearchArea generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class ResearchArea implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "great_rarea_id")
	private GreatRarea greatRarea;
	
	private String name;
	private String description;
	
	@OneToMany(mappedBy = "researchArea")
	private Set<ResearchLine> researchLines;

	public ResearchArea() {
	}

	public ResearchArea(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public ResearchArea(long id, GreatRarea greatRarea, String name, String description, Set<ResearchLine> researchLines) {
		this.id = id;
		this.greatRarea = greatRarea;
		this.name = name;
		this.description = description;
		this.researchLines = researchLines;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public GreatRarea getGreatRarea() {
		return this.greatRarea;
	}

	public void setGreatRarea(GreatRarea greatRarea) {
		this.greatRarea = greatRarea;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ResearchLine> getResearchLines() {
		return this.researchLines;
	}

	public void setResearchLines(Set<ResearchLine> researchLines) {
		this.researchLines = researchLines;
	}

}
