package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ResourceVisibilities generated by hbm2java
 */
public class ResourceVisibilities implements java.io.Serializable {

	private long id;
	private String visibility;
	private Set resources = new HashSet(0);

	public ResourceVisibilities() {
	}

	public ResourceVisibilities(long id, String visibility) {
		this.id = id;
		this.visibility = visibility;
	}

	public ResourceVisibilities(long id, String visibility, Set resources) {
		this.id = id;
		this.visibility = visibility;
		this.resources = resources;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getVisibility() {
		return this.visibility;
	}

	public void setVisibility(String visibility) {
		this.visibility = visibility;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

}
