package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import javax.persistence.EmbeddedId;
/**
 * RgroupLeaders generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;

@Entity
public class RgroupLeaders implements java.io.Serializable {

	@EmbeddedId
	private RgroupLeadersId id;
	private ResearchGroup researchGroup;
	private String leaderCitizenId;
	private String leaderNationality;
	private String leaderSecondLastName;
	private String leaderCountryOfBirth;

	public RgroupLeaders() {
	}

	public RgroupLeaders(RgroupLeadersId id, ResearchGroup researchGroup, String leaderCitizenId,
			String leaderNationality, String leaderCountryOfBirth) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.leaderCitizenId = leaderCitizenId;
		this.leaderNationality = leaderNationality;
		this.leaderCountryOfBirth = leaderCountryOfBirth;
	}

	public RgroupLeaders(RgroupLeadersId id, ResearchGroup researchGroup, String leaderCitizenId,
			String leaderNationality, String leaderSecondLastName, String leaderCountryOfBirth) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.leaderCitizenId = leaderCitizenId;
		this.leaderNationality = leaderNationality;
		this.leaderSecondLastName = leaderSecondLastName;
		this.leaderCountryOfBirth = leaderCountryOfBirth;
	}

	public RgroupLeadersId getId() {
		return this.id;
	}

	public void setId(RgroupLeadersId id) {
		this.id = id;
	}

	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	public String getLeaderCitizenId() {
		return this.leaderCitizenId;
	}

	public void setLeaderCitizenId(String leaderCitizenId) {
		this.leaderCitizenId = leaderCitizenId;
	}

	public String getLeaderNationality() {
		return this.leaderNationality;
	}

	public void setLeaderNationality(String leaderNationality) {
		this.leaderNationality = leaderNationality;
	}

	public String getLeaderSecondLastName() {
		return this.leaderSecondLastName;
	}

	public void setLeaderSecondLastName(String leaderSecondLastName) {
		this.leaderSecondLastName = leaderSecondLastName;
	}

	public String getLeaderCountryOfBirth() {
		return this.leaderCountryOfBirth;
	}

	public void setLeaderCountryOfBirth(String leaderCountryOfBirth) {
		this.leaderCountryOfBirth = leaderCountryOfBirth;
	}

}
