package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Date;

import javax.persistence.EmbeddedId;
/**
 * RgroupUsers generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;

@Entity
public class RgroupUsers implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	private RgroupUsersId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("researchGroupId")
	@JoinColumn(name = "research_project_id")
	private ResearchGroup researchGroup;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("usersId")
	@JoinColumn(name = "users_id")
	private Users users;
	
	private Date userEntry;
	private Date userExit;

	public RgroupUsers() {
	}

	public RgroupUsers(RgroupUsersId id, ResearchGroup researchGroup, Users users, Date userEntry) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.users = users;
		this.userEntry = userEntry;
	}

	public RgroupUsers(RgroupUsersId id, ResearchGroup researchGroup, Users users, Date userEntry, Date userExit) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.users = users;
		this.userEntry = userEntry;
		this.userExit = userExit;
	}

	public RgroupUsersId getId() {
		return this.id;
	}

	public void setId(RgroupUsersId id) {
		this.id = id;
	}

	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getUserEntry() {
		return this.userEntry;
	}

	public void setUserEntry(Date userEntry) {
		this.userEntry = userEntry;
	}

	public Date getUserExit() {
		return this.userExit;
	}

	public void setUserExit(Date userExit) {
		this.userExit = userExit;
	}

}
