package co.edu.icesi.researchgroupmanagement.model;

import javax.persistence.EmbeddedId;
/**
 * RRprojectUser generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "rproject_users")
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class RprojectUser implements java.io.Serializable {
	private static final Long serialVersionUID = 1L;

	@EmbeddedId
	private RprojectUserId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("researchProjectId")
	@JoinColumn(name = "research_project_id")
	private ResearchProject researchProject;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("userId")
	@JoinColumn(name = "users_id")
	private User user;
	
	private String memberRole;

}
