package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:23:43 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * RprojectStatus generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class RprojectStatus implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private String status;
	private Set researchProjects = new HashSet(0);

	public RprojectStatus() {
	}

	public RprojectStatus(long id, String status) {
		this.id = id;
		this.status = status;
	}

	public RprojectStatus(long id, String status, Set researchProjects) {
		this.id = id;
		this.status = status;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set researchProjects) {
		this.researchProjects = researchProjects;
	}

}
