package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * RprojectTypes generated by hbm2java
 */
import javax.persistence.OneToMany;

@Entity
public class RprojectTypes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String type;
	
	@OneToMany(mappedBy = "rprojectType")
	private Set<ResearchProject> researchProjects;

	public RprojectTypes() {
	}

	public RprojectTypes(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public RprojectTypes(long id, String type, Set<ResearchProject> researchProjects) {
		this.id = id;
		this.type = type;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<ResearchProject> getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set<ResearchProject> researchProjects) {
		this.researchProjects = researchProjects;
	}

}
