package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

/**
 * RprojectGoal generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class RprojectGoal implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private ResearchProject researchProject;
	private String description;
	private char isFinished;

	public RprojectGoal() {
	}

	public RprojectGoal(long id, ResearchProject researchProject, String description, char isFinished) {
		this.id = id;
		this.researchProject = researchProject;
		this.description = description;
		this.isFinished = isFinished;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ResearchProject getResearchProject() {
		return this.researchProject;
	}

	public void setResearchProject(ResearchProject researchProject) {
		this.researchProject = researchProject;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public char getIsFinished() {
		return this.isFinished;
	}

	public void setIsFinished(char isFinished) {
		this.isFinished = isFinished;
	}

}
