package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

/**
 * RprojectUsers generated by hbm2java
 */
public class RprojectUsers implements java.io.Serializable {

	private RprojectUsersId id;
	private ResearchProject researchProject;
	private Users users;
	private String memberRole;

	public RprojectUsers() {
	}

	public RprojectUsers(RprojectUsersId id, ResearchProject researchProject, Users users, String memberRole) {
		this.id = id;
		this.researchProject = researchProject;
		this.users = users;
		this.memberRole = memberRole;
	}

	public RprojectUsersId getId() {
		return this.id;
	}

	public void setId(RprojectUsersId id) {
		this.id = id;
	}

	public ResearchProject getResearchProject() {
		return this.researchProject;
	}

	public void setResearchProject(ResearchProject researchProject) {
		this.researchProject = researchProject;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getMemberRole() {
		return this.memberRole;
	}

	public void setMemberRole(String memberRole) {
		this.memberRole = memberRole;
	}

}
