package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import javax.persistence.EmbeddedId;
/**
 * RprojectUsers generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;

@Entity
public class RprojectUsers implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	private RprojectUsersId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("researchProjectId")
	@JoinColumn(name = "research_project_id")
	private ResearchProject researchProject;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("usersId")
	@JoinColumn(name = "users_id")
	private Users users;
	
	private String memberRole;

	public RprojectUsers() {
	}

	public RprojectUsers(RprojectUsersId id, ResearchProject researchProject, Users users, String memberRole) {
		this.id = id;
		this.researchProject = researchProject;
		this.users = users;
		this.memberRole = memberRole;
	}

	public RprojectUsersId getId() {
		return this.id;
	}

	public void setId(RprojectUsersId id) {
		this.id = id;
	}

	public ResearchProject getResearchProject() {
		return this.researchProject;
	}

	public void setResearchProject(ResearchProject researchProject) {
		this.researchProject = researchProject;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getMemberRole() {
		return this.memberRole;
	}

	public void setMemberRole(String memberRole) {
		this.memberRole = memberRole;
	}

}
