package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * RprojectStatus generated by hbm2java
 */
import javax.persistence.OneToMany;

@Entity
public class RprojectStatus implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String status;
	
	@OneToMany(mappedBy = "rprojectStatus")
	private Set<ResearchProject> researchProjects;

	public RprojectStatus() {
	}

	public RprojectStatus(long id, String status) {
		this.id = id;
		this.status = status;
	}

	public RprojectStatus(long id, String status, Set<ResearchProject> researchProjects) {
		this.id = id;
		this.status = status;
		this.researchProjects = researchProjects;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<ResearchProject> getResearchProjects() {
		return this.researchProjects;
	}

	public void setResearchProjects(Set<ResearchProject> researchProjects) {
		this.researchProjects = researchProjects;
	}

}
