package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.sql.Date;

import javax.persistence.EmbeddedId;
/**
 * RRprojectUser generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "project_rproject_status")
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class RprojectRprojectStatus implements java.io.Serializable {

	private static final Long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "RPROJECT_RPROJECT_STATUS_ID_GENERATOR", allocationSize = 1, sequenceName = "RPROJECT_RPROJECT_STATUS_ID_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "RPROJECT_RPROJECT_STATUS_ID_GENERATOR")
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "rRprojectUser"}, allowSetters = true)
	private ResearchProject researchProject;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "researchProjects"}, allowSetters = true)
	private RprojectStatus rprojectStatus;
	
	private Date changeDate;
}