// default package
// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

/**
 * RprojectRpapersId generated by hbm2java
 */
public class RprojectRpapersId implements java.io.Serializable {

	private long researchProjectId;
	private long researchPaperId;

	public RprojectRpapersId() {
	}

	public RprojectRpapersId(long researchProjectId, long researchPaperId) {
		this.researchProjectId = researchProjectId;
		this.researchPaperId = researchPaperId;
	}

	public long getResearchProjectId() {
		return this.researchProjectId;
	}

	public void setResearchProjectId(long researchProjectId) {
		this.researchProjectId = researchProjectId;
	}

	public long getResearchPaperId() {
		return this.researchPaperId;
	}

	public void setResearchPaperId(long researchPaperId) {
		this.researchPaperId = researchPaperId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RprojectRpapersId))
			return false;
		RprojectRpapersId castOther = (RprojectRpapersId) other;

		return (this.getResearchProjectId() == castOther.getResearchProjectId())
				&& (this.getResearchPaperId() == castOther.getResearchPaperId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResearchProjectId();
		result = 37 * result + (int) this.getResearchPaperId();
		return result;
	}

}
