package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import javax.persistence.EmbeddedId;
/**
 * RprojectRpapers generated by hbm2java
 */
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;

@Entity
public class RprojectRpapers implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	private RprojectRpapersId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("researchPaperId")
	@JoinColumn(name = "research_paper_id")
	private ResearchPaper researchPaper;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @MapsId("researchProjectId")
	@JoinColumn(name = "research_project_id")
	private ResearchProject researchProject;
	
	private byte[] isProjectMember;

	public RprojectRpapers() {
	}

	public RprojectRpapers(RprojectRpapersId id, ResearchPaper researchPaper, ResearchProject researchProject,
			byte[] isProjectMember) {
		this.id = id;
		this.researchPaper = researchPaper;
		this.researchProject = researchProject;
		this.isProjectMember = isProjectMember;
	}

	public RprojectRpapersId getId() {
		return this.id;
	}

	public void setId(RprojectRpapersId id) {
		this.id = id;
	}

	public ResearchPaper getResearchPaper() {
		return this.researchPaper;
	}

	public void setResearchPaper(ResearchPaper researchPaper) {
		this.researchPaper = researchPaper;
	}

	public ResearchProject getResearchProject() {
		return this.researchProject;
	}

	public void setResearchProject(ResearchProject researchProject) {
		this.researchProject = researchProject;
	}

	public byte[] getIsProjectMember() {
		return this.isProjectMember;
	}

	public void setIsProjectMember(byte[] isProjectMember) {
		this.isProjectMember = isProjectMember;
	}

}
