package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * SciTiNationalProgram generated by hbm2java
 */
public class SciTiNationalProgram implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private Set researchGroups = new HashSet(0);

	public SciTiNationalProgram() {
	}

	public SciTiNationalProgram(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public SciTiNationalProgram(long id, String name, String description, Set researchGroups) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.researchGroups = researchGroups;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set researchGroups) {
		this.researchGroups = researchGroups;
	}

}
