package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * StudentProgram generated by hbm2java
 */
import javax.persistence.ManyToMany;

@Entity
public class StudentProgram implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String name;
	
	@ManyToMany(mappedBy = "studentPrograms")
	private Set<Users> users;

	public StudentProgram() {
	}

	public StudentProgram(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public StudentProgram(long id, String name, Set<Users> userses) {
		this.id = id;
		this.name = name;
		this.users = userses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Users> getUserses() {
		return this.users;
	}

	public void setUserses(Set<Users> userses) {
		this.users = userses;
	}

}
