package co.edu.icesi.researchgroupmanagement.model;
// Generated Oct 22, 2022, 7:53:51 PM by Hibernate Tools 5.6.7.Final

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * UserTypes generated by hbm2java
 */
import javax.persistence.OneToMany;

@Entity
public class UserTypes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	
	private String type;
	
	@OneToMany(mappedBy = "userType")
	private Set<Users> users;

	public UserTypes() {
	}

	public UserTypes(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public UserTypes(long id, String type, Set<Users> users) {
		this.id = id;
		this.type = type;
		this.users = users;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Users> getUserses() {
		return this.users;
	}

	public void setUserses(Set<Users> userses) {
		this.users = userses;
	}

}
