package co.edu.icesi.researchgroupmanagement.model;

// Generated Oct 15, 2022, 11:56:22 PM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy= GenerationType.SEQUENCE)
	private long id;
	private UserTypes userTypes;
	private String username;
	private String firstName;
	private String lastName;
	private Date dob;
	private String password;
	private String email;
	private byte[] userPicture;
	private Set admissionRequests = new HashSet(0);
	private Set researchGroups = new HashSet(0);
	private Set rgroupUserses = new HashSet(0);
	private Set studentPrograms = new HashSet(0);
	private Set resources = new HashSet(0);
	private Set rprojectUserses = new HashSet(0);

	public Users() {
	}

	public Users(long id, String username, String firstName, String lastName, Date dob, String password, String email) {
		this.id = id;
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.password = password;
		this.email = email;
	}

	public Users(long id, UserTypes userTypes, String username, String firstName, String lastName, Date dob,
			String password, String email, byte[] userPicture, Set admissionRequests, Set researchGroups,
			Set rgroupUserses, Set studentPrograms, Set resources, Set rprojectUserses) {
		this.id = id;
		this.userTypes = userTypes;
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.password = password;
		this.email = email;
		this.userPicture = userPicture;
		this.admissionRequests = admissionRequests;
		this.researchGroups = researchGroups;
		this.rgroupUserses = rgroupUserses;
		this.studentPrograms = studentPrograms;
		this.resources = resources;
		this.rprojectUserses = rprojectUserses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public UserTypes getUserTypes() {
		return this.userTypes;
	}

	public void setUserTypes(UserTypes userTypes) {
		this.userTypes = userTypes;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public byte[] getUserPicture() {
		return this.userPicture;
	}

	public void setUserPicture(byte[] userPicture) {
		this.userPicture = userPicture;
	}

	public Set getAdmissionRequests() {
		return this.admissionRequests;
	}

	public void setAdmissionRequests(Set admissionRequests) {
		this.admissionRequests = admissionRequests;
	}

	public Set getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set researchGroups) {
		this.researchGroups = researchGroups;
	}

	public Set getRgroupUserses() {
		return this.rgroupUserses;
	}

	public void setRgroupUserses(Set rgroupUserses) {
		this.rgroupUserses = rgroupUserses;
	}

	public Set getStudentPrograms() {
		return this.studentPrograms;
	}

	public void setStudentPrograms(Set studentPrograms) {
		this.studentPrograms = studentPrograms;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

	public Set getRprojectUserses() {
		return this.rprojectUserses;
	}

	public void setRprojectUserses(Set rprojectUserses) {
		this.rprojectUserses = rprojectUserses;
	}

}
